// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RunCutWeb.Infrastructure.Data;

#nullable disable

namespace RunCutWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260206120000_AddDDateTable")]
    partial class AddDDateTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RunCutWeb.Domain.Entities.CalendarDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DataSetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExceptionType")
                        .HasColumnType("int");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DataSetId", "ServiceId", "Date");

                    b.ToTable("CalendarDates");
                });

            modelBuilder.Entity("RunCutWeb.Domain.Entities.DDate", b =>
                {
                    b.Property<int>("DateKey")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DateKey");

                    b.ToTable("d_Date", (string)null);
                });

            modelBuilder.Entity("RunCutWeb.Domain.Entities.DataSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("DataSets");
                });

            modelBuilder.Entity("RunCutWeb.Domain.Entities.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgencyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataSetId")
                        .HasColumnType("int");

                    b.Property<string>("RouteColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RouteLongName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteTextColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RouteType")
                        .HasColumnType("int");

                    b.Property<string>("RouteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DataSetId", "RouteId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("RunCutWeb.Domain.Entities.Stop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DataSetId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationType")
                        .HasColumnType("int");

                    b.Property<string>("ParentStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("StopLat")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("StopLon")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("StopName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopTimeZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WheelchairBoarding")
                        .HasColumnType("int");

                    b.Property<string>("ZoneId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DataSetId", "StopId");

                    b.ToTable("Stops");
                });

            modelBuilder.Entity("RunCutWeb.Domain.Entities.StopTiming", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArrivalTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataSetId")
                        .HasColumnType("int");

                    b.Property<string>("DepartureTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DropOffType")
                        .HasColumnType("int");

                    b.Property<int?>("PickupType")
                        .HasColumnType("int");

                    b.Property<decimal?>("ShapeDistTraveled")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("StopHeadsign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StopId1")
                        .HasColumnType("int");

                    b.Property<int?>("StopSequence")
                        .HasColumnType("int");

                    b.Property<int?>("Timepoint")
                        .HasColumnType("int");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TripId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StopId1");

                    b.HasIndex("TripId1");

                    b.HasIndex("DataSetId", "TripId", "StopSequence");

                    b.ToTable("StopTimings");
                });

            modelBuilder.Entity("RunCutWeb.Domain.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BikesAllowed")
                        .HasColumnType("int");

                    b.Property<string>("BlockId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataSetId")
                        .HasColumnType("int");

                    b.Property<int?>("DirectionId")
                        .HasColumnType("int");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RouteId1")
                        .HasColumnType("int");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShapeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TripHeadsign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TripShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WheelchairAccessible")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RouteId1");

                    b.HasIndex("DataSetId", "TripId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("RunCutWeb.Domain.Entities.CalendarDate", b =>
                {
                    b.HasOne("RunCutWeb.Domain.Entities.DataSet", "DataSet")
                        .WithMany("CalendarDates")
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSet");
                });

            modelBuilder.Entity("RunCutWeb.Domain.Entities.Route", b =>
                {
                    b.HasOne("RunCutWeb.Domain.Entities.DataSet", "DataSet")
                        .WithMany("Routes")
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSet");
                });

            modelBuilder.Entity("RunCutWeb.Domain.Entities.Stop", b =>
                {
                    b.HasOne("RunCutWeb.Domain.Entities.DataSet", "DataSet")
                        .WithMany("Stops")
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSet");
                });

            modelBuilder.Entity("RunCutWeb.Domain.Entities.StopTiming", b =>
                {
                    b.HasOne("RunCutWeb.Domain.Entities.DataSet", "DataSet")
                        .WithMany("StopTimings")
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RunCutWeb.Domain.Entities.Stop", "Stop")
                        .WithMany("StopTimings")
                        .HasForeignKey("StopId1");

                    b.HasOne("RunCutWeb.Domain.Entities.Trip", "Trip")
                        .WithMany("StopTimings")
                        .HasForeignKey("TripId1");

                    b.Navigation("DataSet");

                    b.Navigation("Stop");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("RunCutWeb.Domain.Entities.Trip", b =>
                {
                    b.HasOne("RunCutWeb.Domain.Entities.DataSet", "DataSet")
                        .WithMany("Trips")
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RunCutWeb.Domain.Entities.Route", "Route")
                        .WithMany("Trips")
                        .HasForeignKey("RouteId1");

                    b.Navigation("DataSet");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("RunCutWeb.Domain.Entities.DataSet", b =>
                {
                    b.Navigation("CalendarDates");

                    b.Navigation("Routes");

                    b.Navigation("StopTimings");

                    b.Navigation("Stops");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("RunCutWeb.Domain.Entities.Route", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("RunCutWeb.Domain.Entities.Stop", b =>
                {
                    b.Navigation("StopTimings");
                });

            modelBuilder.Entity("RunCutWeb.Domain.Entities.Trip", b =>
                {
                    b.Navigation("StopTimings");
                });
#pragma warning restore 612, 618
        }
    }
}
